### ISSUE TITLE
No Sudo and root

### ISSUE THREAD

**Issue by sebastiangruben** [ysdragon/Pterodactyl-VPS-Egg#8] opened 2023-10-21 17:24 UTC
<img width="531" alt="image" src="https://github.com/ysdragon/Pterodactyl-VPS-Egg/assets/58784842/f14e05bd-e6fc-4a1d-b6c3-25ce58feef88">

I have done everything as you say in the instructions, yet I can't do an "apt-get update" or from "sudo apt-get update". Also I can not install anything. See the picture

**Comment by ysdragon** [comment] 2023-10-23 20:52
I think there's something wrong with the container image, i will fix it when i have time, thx.

**Comment by ysdragon** [comment] 2023-10-24 21:13
Closed because it's a duplicate of this [issue](https://github.com/ysdragon/Pterodactyl-VPS-Egg/issues/7)

**Closed by ysdragon** 2023-10-24 21:13 UTC
